In [1]:
import numpy as np

A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

C = [[0,0],
     [0,0]]

for i in range(2):
    for j in range(2):
        C[i][j] = A[i][j] + B[i][j]

A = np.array(A)
B = np.array(B)
C = A + B

print("Matrix A")
print(A)

print("Matrix B")
print(B)

print("Addition of Matrix A and B")
print(C)

        

Matrix A
[[1 2]
 [3 4]]
Matrix B
[[5 6]
 [7 8]]
Addition of Matrix A and B
[[ 6  8]
 [10 12]]
